# Generated by Django 4.0.1 on 2025-05-19 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0013_alter_watermark_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_banner', models.ImageField(default='/images/default/default_hero_banner.png', upload_to='images')),
                ('hero_image', models.ImageField(default='/images/default/default_hero_image.png', upload_to='images')),
                ('greeting_title', models.CharField(default='Welcome to Prokope.io!', max_length=200, null=True)),
                ('greeting_description', models.TextField(default='My personal portfolio for my thoughts and achievements.', null=True)),
                ('about_me_title', models.CharField(default='About Jay', max_length=200, null=True)),
                ('about_me_description', models.TextField(default="I'm from Kansas, served in the Marines, and work as a software developer intern while studying at Kansas State University", null=True)),
                ('about_prokope_title', models.CharField(default="What is 'Prokope'", max_length=200, null=True)),
                ('about_prokope_description', models.TextField(default="Prokope means 'to chop down what gets in the way'", null=True)),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Index',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('updated_on', models.DateField(default=django.utils.timezone.now)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('thumb', models.ImageField(blank=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=199)),
                ('content', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250)),
                ('galleries', models.ManyToManyField(to='photologue.Gallery')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
    ]
