# Generated by Django 4.0.1 on 2025-05-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
