# Generated by Django 4.0.1 on 2025-05-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
    ]
