# Generated by Django 4.0.1 on 2025-05-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_photogallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
