# Generated by Django 4.0 on 2021-12-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Image',
        ),
    ]
