# Generated by Django 4.0 on 2021-12-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
        ('blog', '0002_rename_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phogo_gallery', to='photologue.photo'),
        ),
    ]
