# Generated by Django 4.0.1 on 2022-01-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_on_alter_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdescription',
            name='hero_banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='indexdescription',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
