# Generated by Django 4.0 on 2022-01-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='IndexDescription',
        ),
    ]
