# Generated by Django 4.0 on 2022-01-01 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_index_indexdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdescription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
