# Generated by Django 4.0 on 2022-01-01 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_indexdescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdescription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 23, 10, 31, 308393)),
        ),
    ]
