# Generated by Django 4.0 on 2022-01-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_indexdescription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdescription',
            name='date',
        ),
    ]
