# Generated by Django 4.0.1 on 2022-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_indexdescription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdescription',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='indexdescription',
            name='plans',
        ),
        migrations.AddField(
            model_name='indexdescription',
            name='about_me_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='indexdescription',
            name='about_me_title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexdescription',
            name='greeting_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='indexdescription',
            name='greeting_title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexdescription',
            name='plans_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='indexdescription',
            name='plans_title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
