# Generated by Django 4.0.1 on 2022-01-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
        ('blog', '0012_alter_post_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PhotoGallery',
        ),
    ]
