# Generated by Django 5.2 on 2025-05-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_rename_photogallery_countryalbum"),
        ("photologue", "0013_alter_watermark_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CountryAlbum",
            new_name="PhotoGallery",
        ),
    ]
