# Generated by Django 5.2.1 on 2025-05-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photologue", "0013_alter_watermark_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=199)),
                ("content", models.TextField()),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=250),
                ),
                ("galleries", models.ManyToManyField(to="photologue.gallery")),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
                "ordering": ["country"],
            },
        ),
    ]
