# Generated by Django 5.2 on 2025-05-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("photologue", "0013_alter_watermark_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PhotoGallery",
            new_name="CountryAlbum",
        ),
    ]
