# Generated by Django 4.0.1 on 2025-05-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['country'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
    ]
