# Generated by Django 5.2 on 2025-05-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_city_country_cityphoto_city_country_countryalbum_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhotoGallery",
        ),
    ]
