# Generated by Django 5.2.1 on 2025-05-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_banner",
                    models.ImageField(
                        default="/images/default/default_hero_banner.png",
                        upload_to="images",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        default="/images/default/default_hero_image.png",
                        upload_to="images",
                    ),
                ),
                (
                    "greeting_title",
                    models.CharField(
                        default="Welcome to Prokope.io!", max_length=200, null=True
                    ),
                ),
                (
                    "greeting_description",
                    models.TextField(
                        default="My personal portfolio for my thoughts and achievements.",
                        null=True,
                    ),
                ),
                (
                    "about_me_title",
                    models.CharField(default="About Jay", max_length=200, null=True),
                ),
                (
                    "about_me_description",
                    models.TextField(
                        default=(
                            "I'm from Kansas, served in the Marines, and work as a software ",
                            "developer intern while studying at Kansas State University",
                        ),
                        null=True,
                    ),
                ),
                (
                    "about_prokope_title",
                    models.CharField(
                        default="What is 'Prokope'", max_length=200, null=True
                    ),
                ),
                (
                    "about_prokope_description",
                    models.TextField(
                        default="Prokope means 'to chop down what gets in the way'",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Index",
                "verbose_name_plural": "Index",
            },
        ),
    ]
