# Generated by Django 5.2 on 2026-06-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="hero_banner",
            field=models.ImageField(
                default="/images/default/default_hero_banner.webp", upload_to="images"
            ),
        ),
    ]
