# Generated by Django 4.0.1 on 2025-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='about_me_description',
            field=models.TextField(default=("I'm from Kansas, served in the Marines, and work as a software ", 'developer intern while studying at Kansas State University'), null=True),
        ),
    ]
