# Generated by Django 5.2 on 2026-07-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_index_hero_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='hero_banner',
            field=models.ImageField(default='images/default/default_hero_banner.webp', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='index',
            name='hero_image',
            field=models.ImageField(default='images/default/default_hero_image.png', upload_to='images'),
        ),
    ]
