# Generated by Django 5.2 on 2026-07-03 21:56

from django.db import migrations
from django.db.models import F, Value, Func


def strip_leading_slash(apps, schema_editor):
    Index = apps.get_model('index', 'Index')
    Index.objects.filter(hero_banner__startswith='/').update(
        hero_banner=Func(F('hero_banner'), Value('/'), function='ltrim')
    )
    Index.objects.filter(hero_image__startswith='/').update(
        hero_image=Func(F('hero_image'), Value('/'), function='ltrim')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_index_hero_banner_alter_index_hero_image'),
    ]

    operations = [
        migrations.RunPython(strip_leading_slash, migrations.RunPython.noop),
    ]
