# Generated by Django 5.2 on 2026-07-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cleanup_leading_slash_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='about_me_description',
            field=models.TextField(default="I'm from Kansas, served in the Marines, and work as a software developer intern while studying at Kansas State University", null=True),
        ),
    ]
